---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/advertisements":
    get:
      summary: list advertisements
      responses:
        '200':
          description: successful
    post:
      summary: create advertisement
      parameters:
      - name: advertisement
        in: body
        schema:
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            price:
              type: number
            phone_contact:
              type: string
            email_contact:
              type: string
            user_id:
              type: string
            images:
              type: array
              items:
                type: string
                format: binary
          required:
          - title
          - description
          - price
          - phone_contact
          - email_contact
          - user_id
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
  "/api/v1/advertisements/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show advertisement
      responses:
        '200':
          description: successful
        '404':
          description: not found
    patch:
      summary: update advertisement
      parameters:
      - name: advertisement
        in: body
        schema:
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            price:
              type: number
            phone_contact:
              type: string
            email_contact:
              type: string
            user_id:
              type: string
            images:
              type: array
              items:
                type: string
                format: binary
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable entity
    delete:
      summary: delete advertisement
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: https://{defaultHost}
  variables: {}
